In [2]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/version/__init__.py'>


**What is a tensor?**
A tensor is a vector that is generalized to higher dimensions. A tensor represents a partially defined computation that will eventually lead into a value. Each tensor has a datatype and a shape. 

Below is an example of creating tensors. (Note that the example defined below in the next cell, demonstrates tensors with just one item, so they're shape is 1 and they're a scalar. A scalar values means its just one value. Vector values means its more than one number)


In [3]:
string = tf.Variable("some string", tf.string)  #tf.Variable(value, datatype)
number = tf.Variable(12345, tf.int16)
floating  = tf.Variable(3.1234, tf.float64)

# *Rank/Dimension*
The rank or dimension of a tensor simply refers to the number of items in the tensor. The tensors created above have rank 0 (1 item is considered to be rank 0, and its a scalar). An interesting thing to note is that whenever you have a list, it is immediately considered as atleast 1 (even if the list has only one element or n items). Look at examples below for more clarification on what I mean.




In [10]:
tensor1 = tf.Variable(["some string", "humbaba", "gilgamesh"], tf.string)  #this is of rank 1 even though the list contains more than 1 item
tensor2 = tf.Variable([12345], tf.int16) #this is also considered as rank 1 even 
#though the array has only element. If 12345 was not in a list then the rank would be 0
tensor3  = tf.Variable([["hi", "hello","yo"],["hi","hello","hi"],["yo","whats","up"]], tf.string) #this is of rank 2 as the deepest level of nesting is 2
#if i had a list inside a list inside a list, the rank would be 3 (look at example below)
tensor4 = tf.Variable([[["hello"]]], tf.string)



In [8]:
tf.rank(tensor4)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

# ***Shape of a Tensor***
The shape of the tensor tells us how many elements there are in each dimension. 

In [14]:
tensorshape = tf.Variable([["hello"]],tf.string)
tensorshape1 = tf.Variable([["hello"],["whatsup"]],tf.string)

In [15]:
tensorshape.shape #first parameter of the output tells us how many dimensions are there, the second parameter tells us the number of items in each dimension

TensorShape([1, 1])

# ***Reshaping a tensor***

In [17]:
tensor_one = tf.ones([1,2,3]) #creates a tensor with all ones (hence the tf.ones), [1,2,3] means 1 list with 2 sublists each with 3 elements
tensor_two = tf.reshape(tensor_one, [2,3,1]) #reshapes tensor_one to a tensor with 2 lists, each list with 3 sublists, each with 1 element 
tensor_three = tf.reshape(tensor_two, [3,-1]) #-1 tells the tensor to calculate the size of the dimension in that place,this will reshape the tensor to [3,2]

In [18]:
print(tensor_one)
print(tensor_two)
print(tensor_three)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# ***Types of Tensors***
There are multiple types of tensors but some of the most common tensors used are:
1. Variable
2. Constant 
3. Placeholder
4. SpareTensor 




Other than the Variable tensor, all tensors are immutable. 

# ***Evaluating a Tensor***
Since tensors store partially complete computation we need to evaluate its value using a session (as shwon below). 

In [ ]:
with tf.Session as sess: #creates a session using a default graph 
  tensor.eval() #tensor is the name of the tensor you want to evaluate 